language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --remote bundler
  - gem update --system
  - gem install rubocop bundler
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH
  - cargo install cross
  - cd multibit_trie
  - cross build --release --target i686-apple-darwin
  - cross build --release --target i686-pc-windows-gnu
  - cross build --release --target i686-pc-windows-msvc
  - cross build --release --target i686-unknown-linux-gnu
  - cross build --release --target x86_64-apple-darwin
  - cross build --release --target x86_64-pc-windows-gnu
  - cross build --release --target x86_64-pc-windows-msvc
  - cross build --release --target x86_64-unknown-linux-gnu
  - ls -lR target/
script:
  - bundle exec rake
