services: docker
sudo: required
cache: cargo
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

matrix:
  include:
    - os: osx
      language: ruby
      env: TARGET=x86_64-apple-darwin
    - os: linux
      language: ruby
      env: TARGET=i686-pc-windows-gnu
    - os: linux
      language: ruby
      env: TARGET=x86_64-pc-windows-gnu
    - os: linux
      language: ruby
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      language: ruby
      env: TARGET=i686-unknown-linux-gnu

before_script:
  - gcc -v
  - gem update --remote bundler
  - gem update --system
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - rustup self update
  - rustc -V
  - cargo -V
  - cargo install --force cross
  - cd multibit_trie

script:
  - cross build --target $TARGET --release
  - ls -lR target/
  - bundle exec rake