language: ruby
rvm:
  - 2.6
services:
  - docker
sudo: required

before_install:
  - gem update --remote bundler
  - gem update --system
  - gem install rubocop bundler
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH
  - cargo install cross
  - cd multibit_trie
  - sh cross-compile.sh
  - ls -lR target/
script:
  - bundle exec rake