language: ruby
services: docker
sudo: required
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

os:
  - osx
  - linux

before_script:
  - gcc -v
  - gem update --remote bundler
  - gem update --system
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - rustup self update
  - rustc -V
  - cargo -V
  - cargo install --force cross
  - cd multibit_trie

script:
  - sh compile.sh
  - ls -lR target/
  - bundle exec rake