language: ruby
rvm:
  - 2.6
services:
  - docker
sudo: required
dist: xenial

matrix:
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: stable
      env: TARGET=i686-unknown-linux-gnu
    - rust: stable
      env: TARGET=x86_64-pc-windows-gnu
    - rust: stable
      env: TARGET=i686-pc-windows-gnu

before_install:
  # - gem update --remote bundler
  # - gem update --system
  # - gem install rubocop bundler
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH
  - source ~/.cargo/env
  - rustup self update
  - rustc -V
  - cargo -V
  - cargo install --force cross
  - cd multibit_trie

install:
  - sh compile.sh

script:
  - ls -lR target/