language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
sudo: required
services:
  - docker

matrix:
  include:
    - os: osx
    - os: linux
      dist: xenial

before_install:
  - gem update --remote bundler
  - gem update --system
  - gem install rubocop bundler
  - bundle install
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH
  - source ~/.cargo/env
  - rustup self update
  - rustc -V
  - cargo -V
  - cargo install --force cross
  - cd multibit_trie

install:
  - sh compile.sh
  - cargo build --release
  - ls -lR target/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cp ./target/release/libmultibit_trie.d ../lib/libmultibit_trie.dylib fi

script:
  - bundle exec rake