language: ruby
rvm:
  - 2.6
rust: stable
sudo: required
services:
  - docker

matrix:
  include:
    - os: osx
    #   env: TARGET=x86_64-apple-darwin
    # - env: TARGET=x86_64-unknown-linux-gnu
    # - env: TARGET=i686-unknown-linux-gnu
    # - env: TARGET=x86_64-pc-windows-gnu
    # - env: TARGET=i686-pc-windows-gnu
    - os: linux
      dist: xenial

before_install:
  # - gem update --remote bundler
  # - gem update --system
  # - gem install rubocop bundler
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH
  - source ~/.cargo/env
  - rustup self update
  - rustc -V
  - cargo -V
  - cargo install --force cross
  - cd multibit_trie

install:
  # - cross build --release --target $TARGET
  - sh compile.sh

script:
  - ls -lR target/