language: ruby
os:
  - linux
  - osx
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
services:
  - docker

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Linux
    - os: linux
      dist: xenial

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - gcc -v
  - gem update --remote bundler
  - gem update --system
  - gem install rubocop bundler
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo install cross          ; fi
  - cd multibit_trie
  - sh compile.sh
  - ls -lR target/
script:
  - bundle exec rake
