language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
sudo: required
services:
  - docker

matrix:
  include:
    - os: osx
    - os: linux
      dist: xenial

before_install:
  - gem update --remote bundler
  - gem update --system
  - gem install rubocop bundler
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH
  - source ~/.cargo/env
  - rustup self update
  - rustc -V
  - cargo -V
  - cargo install --force cross
  - cd multibit_trie

install:
  - sh compile.sh

script:
  - ls -lR target/
  - bundle exec rake